#!bash -e

usage() {
  echo "$0 <home|sys>"
}

apply() {
  echo -n "switch? (y/N) "
  read a
  if [ "x$a" = "xy" ]; then
    return 0
  else
    return 1
  fi
}

case "$1" in
  home)
    home-manager build --flake .
    nvd diff /nix/var/nix/profiles/per-user/jamiez/home-manager result
    if apply; then
      home-manager switch --flake .
    fi
    ;;
  sys)
    nixos-rebuild build --flake .
    nvd diff /nix/var/nix/profiles/system result
    if apply; then
      sudo nixos-rebuild switch --flake .
    fi
    ;;
  *)
    ;;
esac
