backup:
    repo: ENC[AES256_GCM,data:qsUpNIJ7tUv2+RxKIZtqX+2BUpwPj3iJ+LMaUeUwEj68z8uSyBXLSekE7mlf,iv:tSuqPHkcFBiFdqLMfjNGDiQfSe4h5avxe56+1FL3G8Y=,tag:z+hIBESHwy8EsqpeTkDpkg==,type:str]
    password: ENC[AES256_GCM,data:kG2zFVg3T0EDXqeBQ9qSWkN7cNNdsT5cqkUHeCDWug==,iv:dF4CZlsEi96UJyAXg1McXkdic6XTduZKfN/QCsYz0ak=,tag:u5u5ex6jzWbwb9oLmN5b0Q==,type:str]
    env: ENC[AES256_GCM,data:mR9IKeBc6N8DN6WcvXLZffdTlE+sPHaMTJVcSp8eofwMLM5ay8NBMkuRC3JgDHJXOFygQpQPP6pZcLdIkwxwTiDDqb7N/92PnEI3X/32aN1VKjqxthL82bfe8Q==,iv:CRfZawUmKcmy4FzO60HGMTQ7RzL+Sr8fOY3UnBC52kE=,tag:C9PLVsImOWlL0A8zyczH0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-06T14:35:37Z"
    mac: ENC[AES256_GCM,data:ABGjFW4Bg2My5r8FKg+0QuX14KmtiRfgaYOXIPf8dOMVKk07XB4BX05hNJRpDfxqB4Q01yfXZYMnxAlybqUM+K+Vo2pmHKkSFc/94EVOAyAfI3aUhXI6ovw33ho0zl9RoiKemCha4bp2OY0v9oeusvgFprrYNknzJMPwkF4ZjVE=,iv:azIP4pim8OQNtrjIwo4DMQLSNUuD1gV8zqZo36HxUYY=,tag:Z98xoEAg2Urjh0SyaPGLGQ==,type:str]
    pgp:
        - created_at: "2024-09-11T21:11:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DsD1/UQjJ+qgSAQdAdgIYI6y3p0OOsdJQhBnnV3HmOWUbXlqheBvVF3PF8iUw
            1B6VUrA9P//xzXZ8WQItczRGcsS/mFHLJ7v6gPem2l9X3/F0Tpl+J+OaE2tEFz2t
            0lwBh2LtrC7VBNZU90+XW9CpQl4Ssg5o6F4Z0/HFo+BjlfwyXDJMvM+JR6zaptIO
            ZiOyLs5obgaiJuHQX7i5isjoDsfZmpeRnKUaxB7a0I3/lUnVm9vq8coadaMfaw==
            =/tXN
            -----END PGP MESSAGE-----
          fp: C32756FA98BAE710FC2616BB4BBCA7023906BA07
        - created_at: "2024-09-11T21:11:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4n64fI2lSsQAQ//Zl2os7fxxwp/51Z6NWttXFq462bLF3FAPiqp+hSvAl2L
            QQ9M9x3MD35fTl8xuszN21XUnFnTN+GK8xAjZTAysqYRkIghsmRTkkmLY6JCQlLI
            naq4OlJClCCuzlJCLjs9Wy+R6/Wow87sE8ih2Mn3J20o6WBxhaw8OiTk1jjs2eBf
            Fa+qxQn3NajLsIgMSCkRWHtLAQyi3DiqGw2XYZqaoEjgD8OrwAbZOMOrL39FaG/v
            7Gizddsb1IPwES+f2GSfeuP69mLy2TR/MdtxX2SRctkr98eKPrQ8cOOt4QZSM3Ls
            SDZ3BT4nh6U3ipVldvU2AzqYtz2A/RAqsy/CO5uvDzrWpdAqhI+aC1w28CIedZzP
            CYYXJ7wg1Y45v18Q2X0VczCIzvdP8Bj/UxvxLCeOrGW2hVQoz+JZ/EGYx16vE6Dn
            mTqvWX2rOUfsmbG4NeexXaCL4F4mp4P1A5D9KV4bRQ3AfRQUIwSdV3a16fB2ciUj
            jhQDKFA+gyvlCZ6P0RJg3zB6Ya832wGfrCaOEcMDHwSs+4DlXKe7s3KlP92K5Nvx
            voGoPNS1zT9+T+UvgTsX+x/Y7bEBlH0e/Lo1Kqv+IMCEgo2zbYazuhwsF0RMX/P8
            2NQ1fxAFKHEBYOPOiyqSvmaUBBxXGCNv8UWXp4DvzH9QyatrQVNoGxrv3mngxTrS
            VgHbovEgZ8i7Gp/fnuFQR+j6VvSEH6Qq4OskZIoXy+WQ3DplCa8Wdv696zHPhPT6
            IH+UVTiA72bxbCL/TO0WUL0NkRhCndmNIthzuToWCXX7BBtLj8yR
            =0JW3
            -----END PGP MESSAGE-----
          fp: 84e6e4d3e78937e083bd7d6e89fae1f236952b10
    unencrypted_suffix: _unencrypted
    version: 3.9.0
